apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc
  labels:
    app: gitlab 
    region: milton 
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
apiVersion: v1
