apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitlab
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab-ce:latest
        name: gitlab-ce
        ports:
        - name: gitlab-http
          containerPort: 80
        - name: gitlab-https
          containerPort: 443
        - name: gitlab-ssh
          containerPort: 22
        volumeMounts:
        - mountPath: "/etc/gitlab"
          name: gitlab-etc
        - mountPath: "/var/log/gitlab"
          name: gitlab-var-log
        - mountPath: "/var/opt/gitlab"
          name: gitlab-var-opt
      volumes:
      - name: gitlab-etc
        persistentVolumeClaim:
          claimName: gitlab-etc
      - name: gitlab-var-log
        persistentVolumeClaim:
          claimName: gitlab-var-log
      - name: gitlab-var-opt
        persistentVolumeClaim:
          claimName: gitlab-var-opt
