apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitlab
    region: milton
  name: gitlab
  namespace: gitlab
spec:
  ports:
    - name: gitlab-http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: gitlab-https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: gitlab-shell
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: gitlab
  type: NodePort
status:
  loadBalancer: {}
